[tool.flakeheaven]
# optionally inherit from remote config (or local if you want)
# base = "https://raw.githubusercontent.com/flakeheaven/flakeheaven/main/pyproject.toml"
# base = "pyproject_base.toml"

# specify any flake8 options. For example, exclude "example.py":
# exclude = ["example.py"]

# make output nice https://github.com/flakeheaven/flakeheaven/blob/main/docs/formatters.md
format = "grouped"

# 80 chars aren't enough in 21 century
max_line_length = 115

# show line of source code in output
show_source = true


# list of plugins and rules for them
[tool.flakeheaven.plugins]
# # include everything in pyflakes except F401
# pyflakes = ["+*", "-F401"]

# # enable only codes from S100 to S199
# flake8-bandit = ["-*", "+S1??"]

# # enable everything that starts from `flake8-`
# "flake8-*" = ["+*"]

# # explicitly disable plugin
# flake8-docstrings = ["-*"]

# include everything in pylint
pylint = ["+*"]


# disable some checks for tests
# [tool.flakeheaven.exceptions."tests/"]
# pycodestyle = ["-F401"]     # disable a check
# pyflakes = ["-*"]           # disable a plugin

# explicitly disable all plugins
# "*" = ["-*"]

# # do not disable `pyflakes` for one file in tests
# [tool.flakeheaven.exceptions."tests/test_example.py"]
# pyflakes = ["+*"]           # enable a plugin


[tool.black]
line-length = 115